"""change public_id to unique=False, as its reference in transaction table not unique identifier.

Revision ID: bc45909b84d8
Revises: 47315da06676
Create Date: 2026-08-19 13:02:57.835027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc45909b84d8'
down_revision: Union[str, Sequence[str], None] = '47315da06676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f('transactions_public_id_key'), 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('transactions_public_id_key'), 'transactions', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('account_types', 'name',
               existing_type=sa.Enum('SAVINGS', 'CHECKING', 'BUSINESS', 'WALLET', name='accounttypename'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
